name: CodeQL

on:
  pull_request:

jobs:
  Analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: github/codeql-action/init@v1
      with:
        languages: javascript
        config-file: ./.github/codeql-analysis.yml
      
    - uses: github/codeql-action/analyze@v1
