name: CI
on: 
  - push
  - workflow_dispatch
#       inputs:
#         logLevel:
#           description: ''     
#           required: true
#           default: 'warning'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build
      - run: npm run lint
